import type { GeneratePdfResult, SavePdfStatus } from '../export/pdfTypes';

export type { SavePdfStatus };

function isTauri(): boolean {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
}

async function saveTauriBytes(bytes: Uint8Array, filename: string): Promise<SavePdfStatus> {
  const { save } = await import('@tauri-apps/plugin-dialog');
  const { writeFile } = await import('@tauri-apps/plugin-fs');
  const path = await save({
    defaultPath: filename,
    filters: [{ name: 'PDF', extensions: ['pdf'] }],
  });
  if (!path) return 'cancelled';
  await writeFile(path, bytes);
  return 'saved';
}

async function downloadWebBytes(bytes: Uint8Array, filename: string): Promise<SavePdfStatus> {
  const blob = new Blob([new Uint8Array(bytes)], { type: 'application/pdf' });
  const picker = (
    window as unknown as {
      showSaveFilePicker?: (opts: {
        suggestedName: string;
        types: { description: string; accept: Record<string, string[]> }[];
      }) => Promise<{
        createWritable: () => Promise<{ write: (data: Blob) => Promise<void>; close: () => Promise<void> }>;
      }>;
    }
  ).showSaveFilePicker;

  if (typeof picker === 'function') {
    try {
      const handle = await picker({
        suggestedName: filename,
        types: [{ description: 'PDF', accept: { 'application/pdf': ['.pdf'] } }],
      });
      const writable = await handle.createWritable();
      await writable.write(blob);
      await writable.close();
      return 'saved';
    } catch (e: unknown) {
      if (e instanceof Error && e.name === 'AbortError') return 'cancelled';
    }
  }

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
  return 'saved';
}

export async function savePdf(
  source: GeneratePdfResult,
  filename: string,
): Promise<SavePdfStatus> {
  if (source.kind === 'printed') {
    return 'printed';
  }
  if (source.kind !== 'bytes') {
    throw new Error('Web PDF export expected generated bytes');
  }
  if (isTauri()) {
    return saveTauriBytes(source.bytes, filename);
  }
  return downloadWebBytes(source.bytes, filename);
}
