import type { GeneratePdfResult, SavePdfStatus } from '../export/pdfTypes';

export type { SavePdfStatus };

function isTauri(): boolean {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
}

async function saveTauriBytes(bytes: Uint8Array, filename: string): Promise<SavePdfStatus> {
  const { save } = await import('@tauri-apps/plugin-dialog');
  const { writeFile } = await import('@tauri-apps/plugin-fs');
  const path = await save({
    defaultPath: filename,
    filters: [{ name: 'PDF', extensions: ['pdf'] }],
  });
  if (!path) return 'cancelled';
  await writeFile(path, bytes);
  return 'saved';
}

export async function savePdf(
  source: GeneratePdfResult,
  filename: string,
): Promise<SavePdfStatus> {
  if (source.kind === 'printed') {
    return 'printed';
  }
  if (source.kind !== 'bytes') {
    throw new Error('Web PDF export expected generated bytes');
  }
  if (!isTauri()) {
    throw new Error('PDF bytes export is only supported in the desktop app');
  }
  return saveTauriBytes(source.bytes, filename);
}
